### PR TITLE
NodeMaterial Revision

### PR DESCRIPTION
**Pull request by sunag**
In order to simplify I would like to propose some changes.

Root nodes like `NormalNode`, `ReflectNode` and `CubeTextureNode` we can put in your external interface only globals parameters, like in `NormalNode`: `VIEW`, `LOCAL` and `GLOBAL` and try prevent `CLEARCOAT`, `BENT` or others characteristics of PBR to that makes this interface a bit more simple to learn and make this a bit more compatible with others nodes like `PhongNode`, since that this can be added in `context`.

Other important thing is the `anisotropy.code` and your sequence. In this case, It is not a complex shader graph, but in others case variables are declared for optimization or other custom nodes is `generate` in `anisotropy.code`. `anisotropy.result` return only inline(final) results.

The sequence of `analyze` and `flow` is very important to `generate` the correct structure of the code, all `analyze` should be executed before of first `flow`, and follow the exact sequence. For example:

```javascript
this.roughness.analyze( builder );
this.metalness.analyze( builder );

// this should follow the same sequence of the analyze, metalness after roughness for example
// any flow should be after all analyze be executed
var roughness = this.roughness.flow( builder, 'f' );
var metalness = this.metalness.flow( builder, 'f' );
```

`sheen.code` and sequence I revised in https://github.com/mrdoob/three.js/pull/17265

### CODE REVIEW

**Comment by DanielSturk** [comment]
Looks great, but I don't think we should be replacing `viewNormal` with the bent normal in the environment context. Since the bent normal is used only for IBL, I would just add a second `bentNormal` alongside `viewNormal`

**Comment by sunag** [comment]
Hmm, what do you think of `iblViewNormal` ~or in shader `iblNormal`~? seems more suggestive to me since we own `iblIrradiance` too.

**Comment by sunag** [comment]
I will review this detail. 👍

**Comment by DanielSturk** [comment]
`iblViewNormal` is fine, I do prefer something with `bent` and `normal` in the name though, since `bent normal` is the universal term

**Comment by sunag** [comment]
I add `ReflectNode` in `material.environment` input and the result seems the expected
```javascript
carbonMat.environment = new Nodes.ReflectNode( Nodes.ReflectNode.CUBE );
```

If I add a context isolate to IBL `ReflectNode` not will work with anisotropic effect without the `texture.uv` context.

I think that at the moment we could leave it like this?

image

**Comment by DanielSturk** [comment]
@sunag For some reason I thought `contextEnvironment.viewNormal` would affect the direct light's viewNormal, but obviously it only affects the environment, so replacing `viewNormal` is fine. Thank you for your contribution. Merged.

**Comment by sunag** [comment]
@DanielSturk thank you too for your great work.

**Pull request merged**
